version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: deploy/app/Dockerfile
    command: gunicorn djangoproject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - 8000
    env_file: .env
  nginx:
    build: ./deploy/nginx
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - 8899:80
    depends_on:
      - web

volumes:
  static_volume:
